# A sample Gemfile
source "https://rubygems.org"

gem 'rails', '~> 4.2.0'
gem 'mongoid', '~> 4.0.1'
gem 'puma', '~> 2.11.0'
gem 'kaminari', '~> 0.16.2'
gem 'tzinfo', '~> 1.2.2'
gem 'rails-i18n', '~> 4.0.3'
gem 'mongoid_i18n', '~> 0.5.1'
gem 'mongoid_slug', '~> 4.0.0'
gem 'active_model_serializers', '~> 0.9.3'
gem 'devise', '~> 3.4.1'

group :development, :test do
  gem 'ffaker', '~> 1.32.1'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'simplecov', '~> 0.9.1'
  gem 'rspec-rails', '~> 3.2.0'
  gem 'mongoid-rspec', '~> 2.1.0'
  gem 'remarkable_mongoid', '~> 0.6.0'
  gem 'pry-rails', '~> 0.3.2'
  gem 'guard', '~> 2.11.1'
  gem 'guard-bundler', '~> 2.1.0'
  gem 'guard-shell', '~> 0.7.1'
  gem 'terminal-notifier-guard', '~> 1.6.4'
  gem 'brakeman', '~> 3.0.1'
  gem 'guard-brakeman', '~> 0.8.3'
end
